[package]
name = "crypto"
version = "0.1.0"
authors = ["Benjamin Bäumler <benjamin.baeumler@qqwa.de>"]
edition = "2018"

[lib]
name = "crypto_rust"
crate-type = ["staticlib"]

[dependencies]
libc = "0.2.0"
rust-crypto = "0.2.36"

[build-dependencies]
cbindgen = "0.6.6"
